version: '2'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./app.conf:/etc/nginx/conf.d/app.conf
      - .:/var/www/html
    ports:
      - "80:80"
  php-fpm:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "2222:22"
  mysql:
   image: mariadb:10
   restart: always
   volumes:
     - ./mariadb/db/:/var/lib/mysql
     - ./mariadb/mycnf:/etc/mysql/conf.d
   environment:
       MYSQL_ROOT_PASSWORD: IgheaLohbe7Fisaevoongac3i
   ports:
     - 3307:3306 
  adminer:
   image: adminer
   restart: always
   ports:
     - 8080:8080
   links:
     - mysql:db
