version: '2'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./app.conf:/etc/nginx/conf.d/app.conf
      - .:/var/www/html
    ports:
      - "80:80"
  php-fpm:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "2222:22"
  mysql:
   image: mysql:latest
   container_name: lemp_mariadb
   restart: always
   command: mysqld --max_allowed_packet=1024M
   environment:
       MYSQL_ROOT_PASSWORD: root@123
       MYSQL_USER: root
       MYSQL_PASSWORD: root@123
   volumes:
       - './.data/mysql:/var/lib/mysql'
   ports:
     - 3306:3306 
